# Generated by Django 5.2.12 on 2026-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_location_alter_consultation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
